### ISSUE TITLE
illuminate dislikes alex-3

### ISSUE THREAD

**Issue by trofi** [jgm/illuminate#4]
(shifted dep range to allow alex-3 manually)

Looks like it's tied to some alex-provided template:

> Building illuminate-0.1...
> Preprocessing library illuminate-0.1...
> [ 1 of 24] Compiling Text.Highlighting.Illuminate.C ( dist/build/Text/Highlighting/Illuminate/C.hs, dist/build/Text/Highlighting/Illuminate/C.o )
> 
> Text/Highlighting/Illuminate/C.x:84:10:
>     Not in scope: type constructor or class `Lexer'

**Comment by nomeata** [comment]
What is the status of this bug? Is illuminate still in active maintenance?

**Comment by jgm** [comment]
+++ Joachim Breitner [Jul 02 13 09:21 ]:

>    What is the status of this bug? Is illuminate still in active
>    maintenance?

I haven't touched illuminate for years.  I had hoped others would take
interest and help develop and maintain language parsers, but nobody
really did, so I dropped it.
